from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from engine.models import AnalysisScope


class AnalyzerType(Enum):
    """
    Enumeration of all supported static analysis tools.
    """
    SONARQUBE = "sonarqube"
    CPPCHECK = "cppcheck"
    ARDUINO_CLI = "arduino_cli"
    CUSTOM = "custom"


@dataclass(slots=True)
class AnalysisTask:
    """
    Represents a specific analyzer configured to run against targeted paths.
    
    Attributes:
        tool: The specific tool to execute.
        language: The language responsible for creating this task (e.g., Python, C++).
        repository_root: The root path of the repository it operates on.
        target_paths: Specific files or directories the tool should analyze.
                      If empty, implies a scan from the repository root.
        scope: The original requested AnalysisScope.
        options: Any tool-specific CLI arguments, flags, or properties.
    """
    tool: AnalyzerType
    language: str | None
    repository_root: Path
    scope: AnalysisScope
    target_paths: list[Path] = field(default_factory=list)
    options: dict[str, str] = field(default_factory=dict)


@dataclass(slots=True)
class AnalysisPlan:
    """
    The final strategic blueprint generated by the Planner.
    
    This is passed to the execution engine to run the tools.
    
    Attributes:
        repository_name: The name of the analyzed repository.
        repository_path: The absolute path to the repository root.
        tasks: The list of carefully selected and configured analysis tasks.
    """
    repository_name: str
    repository_path: Path
    tasks: list[AnalysisTask] = field(default_factory=list)
